export enum SessionEventType {
  // Lifecycle
  SESSION_CREATED = 'SESSION_CREATED',
  SESSION_STARTED = 'SESSION_STARTED',
  SESSION_ENDING = 'SESSION_ENDING',
  SESSION_ENDED = 'SESSION_ENDED',
  // Participants
  PARTICIPANT_JOINED = 'PARTICIPANT_JOINED',
  PARTICIPANT_LEFT = 'PARTICIPANT_LEFT',
  // Media
  STREAM_STARTED = 'STREAM_STARTED',
  STREAM_ENDED = 'STREAM_ENDED',
  SCREEN_SHARE_STARTED = 'SCREEN_SHARE_STARTED',
  SCREEN_SHARE_ENDED = 'SCREEN_SHARE_ENDED',
  // Lobby
  LOBBY_JOINED = 'LOBBY_JOINED',
  LOBBY_LEFT = 'LOBBY_LEFT',
  // Recording pipeline
  RECORDING_STARTED = 'RECORDING_STARTED',
  RECORDING_ENDED = 'RECORDING_ENDED',
  RECORDING_FAILED = 'RECORDING_FAILED',
  MEDIACONVERT_SUBMITTED = 'MEDIACONVERT_SUBMITTED',
  MEDIACONVERT_COMPLETED = 'MEDIACONVERT_COMPLETED',
  MEDIACONVERT_FAILED = 'MEDIACONVERT_FAILED',
  TRANSCRIBE_SUBMITTED = 'TRANSCRIBE_SUBMITTED',
  TRANSCRIBE_COMPLETED = 'TRANSCRIBE_COMPLETED',
  TRANSCRIBE_FAILED = 'TRANSCRIBE_FAILED',
  AI_SUMMARY_STARTED = 'AI_SUMMARY_STARTED',
  AI_SUMMARY_COMPLETED = 'AI_SUMMARY_COMPLETED',
  AI_SUMMARY_FAILED = 'AI_SUMMARY_FAILED',
  HIGHLIGHT_REEL_STARTED = 'HIGHLIGHT_REEL_STARTED',
  HIGHLIGHT_REEL_COMPLETED = 'HIGHLIGHT_REEL_COMPLETED',
  HIGHLIGHT_REEL_FAILED = 'HIGHLIGHT_REEL_FAILED',
  // Context + AI Agent
  CONTEXT_EVENT_RECEIVED = 'CONTEXT_EVENT_RECEIVED',
  INTENT_FLOW_CREATED = 'INTENT_FLOW_CREATED',
  INTENT_FLOW_COMPLETED = 'INTENT_FLOW_COMPLETED',
  AGENT_JOINED = 'AGENT_JOINED',
  AGENT_SPOKE = 'AGENT_SPOKE',
  AGENT_COMPLETED = 'AGENT_COMPLETED',
  AGENT_LEFT = 'AGENT_LEFT',
  INTENT_EXTRACTED = 'INTENT_EXTRACTED',
  // Moderation
  MODERATION_FLAGGED = 'MODERATION_FLAGGED',
  MODERATION_AUTO_KILLED = 'MODERATION_AUTO_KILLED',
  MODERATION_REVIEWED = 'MODERATION_REVIEWED',
}

export interface SessionEvent {
  eventId: string;
  sessionId: string;
  eventType: SessionEventType;
  timestamp: string;
  sessionRelativeTimeMs?: number;
  actorId?: string;
  actorType?: 'user' | 'system' | 'ai-agent' | 'ivs';
  details?: Record<string, any>;
  sourceAppId?: string;
}
